#!/usr/bin/env bash
# OASYS one-line installer.
# Usage: curl -fsSL https://raw.githubusercontent.com/Olimdk/oasys/main/install.sh | bash
set -euo pipefail

REPO="Olimdk/oasys"
BRANCH="main"
INSTALL_DIR="${OASYS_HOME:-$HOME/.local/share/oasys}"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/oasys"
VENV="$INSTALL_DIR/venv"

info() { echo -e "\033[36m==>\033[0m $*"; }
warn() { echo -e "\033[33mWARNING:\033[0m $*" >&2; }
die()  { echo -e "\033[31mERROR:\033[0m $*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"; }
need git
need python3
need curl

info "Installing OASYS (newest '$BRANCH') to $INSTALL_DIR"

if [ -d "$INSTALL_DIR/.git" ]; then
  info "Existing install found — updating to newest version"
  git -C "$INSTALL_DIR" fetch --all --quiet
  git -C "$INSTALL_DIR" checkout -q "$BRANCH"
  git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
else
  info "Cloning $REPO"
  mkdir -p "$INSTALL_DIR"
  git clone --depth 1 --branch "$BRANCH" "https://github.com/$REPO.git" "$INSTALL_DIR"
fi

if [ ! -d "$VENV" ]; then
  info "Creating virtual environment"
  python3 -m venv "$VENV" || die "Failed to create venv (is python3-venv installed?)"
fi
# shellcheck disable=SC1091
source "$VENV/bin/activate"
info "Installing Python dependencies"
pip install --quiet --upgrade pip
pip install --quiet -r "$INSTALL_DIR/requirements.txt"

if [ ! -f "$INSTALL_DIR/.env" ]; then
  info "Creating .env from example — add your key to $INSTALL_DIR/.env"
  cp "$INSTALL_DIR/.env.example" "$INSTALL_DIR/.env"
fi

mkdir -p "$BIN_DIR"
info "Installing launcher to $LAUNCHER"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# OASYS launcher — generated by install.sh.
set -e
cd "$INSTALL_DIR"
source "$VENV/bin/activate"
ENV_FILE="$INSTALL_DIR/.env"
needs_key() {
  [ ! -f "\$ENV_FILE" ] && return 0
  grep -q "OPENROUTER_API_KEY=your-key-here" "\$ENV_FILE" 2>/dev/null && return 0
  grep -q "OPENROUTER_API_KEY=.\\+" "\$ENV_FILE" 2>/dev/null || return 0
  return 1
}
if [ -t 0 ]; then
  if needs_key; then
    echo "OpenRouter API key required. Get one at https://openrouter.ai/keys"
    read -s -p "Paste your OPENROUTER_API_KEY: " KEY
    echo
    if [ -n "\$KEY" ]; then
      sed -i "s|^OPENROUTER_API_KEY=.*|OPENROUTER_API_KEY=\$KEY|" "\$ENV_FILE"
    fi
  fi
else
  if needs_key; then
    echo "ERROR: OPENROUTER_API_KEY not set in \$ENV_FILE" >&2
    echo "Edit that file and add your key, then re-run 'oasys'." >&2
    exit 1
  fi
fi
exec python -m oasys.app "\$@"
EOF
chmod +x "$LAUNCHER"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) warn "$BIN_DIR is not on your PATH. Add: export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

info "Done. Run 'oasys' to start OASYS."
