#!/usr/bin/env bash
# OASYS launcher — generated by install.sh.
# Runs the OASYS TUI from anywhere; prompts once for the API key if missing.
set -e

INSTALL_DIR="{{INSTALL_DIR}}"
VENV="{{VENV}}"

cd "$INSTALL_DIR"
source "$VENV/bin/activate"

ENV_FILE="$INSTALL_DIR/.env"

needs_key() {
  # returns 0 (true) if the key is missing or still the placeholder
  [ ! -f "$ENV_FILE" ] && return 0
  grep -q "OPENROUTER_API_KEY=your-key-here" "$ENV_FILE" 2>/dev/null && return 0
  grep -q "OPENROUTER_API_KEY=.\+" "$ENV_FILE" 2>/dev/null || return 0
  return 1
}

if [ -t 0 ]; then
  if needs_key; then
    echo "OpenRouter API key required. Get one at https://openrouter.ai/keys"
    read -s -p "Paste your OPENROUTER_API_KEY: " KEY
    echo
    if [ -n "$KEY" ]; then
      sed -i "s|^OPENROUTER_API_KEY=.*|OPENROUTER_API_KEY=$KEY|" "$ENV_FILE"
    fi
  fi
else
  if needs_key; then
    echo "ERROR: OPENROUTER_API_KEY not set in $ENV_FILE" >&2
    echo "Edit that file and add your key, then re-run 'oasys'." >&2
    exit 1
  fi
fi

exec python -m oasys.app "$@"
